export default [
    {
        id:1,
        username:"abc312",
        name:"john",
        points:34,     
        date:"25-2-22",   
    },
    {
        id:2,
        username:"abc31142",
        name:"mark",
        points:22,
        date:"20-2-22",   
    },
    {
        id:3,
        username:"abc3132",
        name:"chris",
        points:43,
        date:"15-2-22",   
    },
    {
        id:4,
        username:"abc3132",
        name:"chris",
        points:43,
        date:"10-2-22",   
    },    
    {
        id:5,
        username:"abc3132",
        name:"chris",
        points:43,
        date:"10-2-22",   
    },  
]